### ISSUE TITLE
Dynamic Meta Tags for SEO

### ISSUE THREAD

**Issue by reaton333** [reaton333/the-crypto-masters-website#37]
Results:
- [x] Have good meta tags for each coin details page
- [x] Good meta tag for coin list
- [x] Main meta tag for home page
- [x] Meta tag for about page
- [x] Meta tag for podcast list page
- [x] Meta tag for podcast episode page
- [x] Hopefully able to share via message cleaning for all above
