### ISSUE TITLE
Create base meta tag in Index.html file for Sharing Purposing

### ISSUE THREAD

**Issue by reaton333** [reaton333/the-crypto-masters-website#41]
- [ ] Link in messages
- [ ] Link on facebook
- [ ] Link on twitter

*** Must be static HTML and not Javascript ****
